import type { Position, Wall } from './gameLogic';

export interface Puzzle {
  id: string;
  title: string;
  description: string;
  maxMoves: number;
  walls: Wall[];
  p1Start: Position;
  p2Start: Position;
}

export const PUZZLES: Puzzle[] = [
  {
    id: 'p1',
    title: 'Premier pas',
    description: 'Atteignez la ligne adverse en un seul coup.',
    maxMoves: 1,
    walls: [],
    p1Start: { r: 7, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p2',
    title: 'Petit détour',
    description: "Un mur bloque la route directe : contournez-le.",
    maxMoves: 3,
    walls: [{ row: 6, col: 4, orientation: 'H' }],
    p1Start: { r: 6, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p3',
    title: 'Sous pression',
    description: 'Un mur vous coupe la route à mi-chemin.',
    maxMoves: 5,
    walls: [{ row: 4, col: 4, orientation: 'H' }],
    p1Start: { r: 4, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p4',
    title: 'Le long chemin',
    description: 'Deux murs vous forcent à ruser pour passer.',
    maxMoves: 5,
    walls: [
      { row: 6, col: 4, orientation: 'H' },
      { row: 6, col: 2, orientation: 'H' },
    ],
    p1Start: { r: 6, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p5',
    title: 'Le grand détour',
    description: 'Un mur double vous oblige à sortir des sentiers battus. Aucune marge d\'erreur.',
    maxMoves: 6,
    walls: [
      { row: 3, col: 4, orientation: 'H' },
      { row: 3, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 3, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p6',
    title: 'Le zigzag',
    description: "Deux rangées presque entièrement bloquées. Traversez tout le plateau en largeur, deux fois.",
    maxMoves: 22,
    walls: [
      { row: 5, col: 0, orientation: 'H' },
      { row: 5, col: 2, orientation: 'H' },
      { row: 5, col: 4, orientation: 'H' },
      { row: 5, col: 6, orientation: 'H' },
      { row: 2, col: 1, orientation: 'H' },
      { row: 2, col: 3, orientation: 'H' },
      { row: 2, col: 5, orientation: 'H' },
      { row: 2, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p7',
    title: 'Le triple barrage',
    description: "Trois rangées à franchir, chacune avec une seule brèche à l'opposé de la précédente.",
    maxMoves: 30,
    walls: [
      { row: 6, col: 0, orientation: 'H' },
      { row: 6, col: 2, orientation: 'H' },
      { row: 6, col: 4, orientation: 'H' },
      { row: 6, col: 6, orientation: 'H' },
      { row: 4, col: 1, orientation: 'H' },
      { row: 4, col: 3, orientation: 'H' },
      { row: 4, col: 5, orientation: 'H' },
      { row: 4, col: 7, orientation: 'H' },
      { row: 2, col: 0, orientation: 'H' },
      { row: 2, col: 2, orientation: 'H' },
      { row: 2, col: 4, orientation: 'H' },
      { row: 2, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p8',
    title: "L'inversion",
    description: "Comme le triple barrage, mais les brèches sont inversées. Ne vous fiez pas à vos habitudes.",
    maxMoves: 30,
    walls: [
      { row: 6, col: 1, orientation: 'H' },
      { row: 6, col: 3, orientation: 'H' },
      { row: 6, col: 5, orientation: 'H' },
      { row: 6, col: 7, orientation: 'H' },
      { row: 4, col: 0, orientation: 'H' },
      { row: 4, col: 2, orientation: 'H' },
      { row: 4, col: 4, orientation: 'H' },
      { row: 4, col: 6, orientation: 'H' },
      { row: 2, col: 1, orientation: 'H' },
      { row: 2, col: 3, orientation: 'H' },
      { row: 2, col: 5, orientation: 'H' },
      { row: 2, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p9',
    title: 'Le grand serpent',
    description: "Quatre rangées, quatre traversées complètes du plateau. Un vrai marathon.",
    maxMoves: 40,
    walls: [
      { row: 7, col: 0, orientation: 'H' },
      { row: 7, col: 2, orientation: 'H' },
      { row: 7, col: 4, orientation: 'H' },
      { row: 7, col: 6, orientation: 'H' },
      { row: 5, col: 1, orientation: 'H' },
      { row: 5, col: 3, orientation: 'H' },
      { row: 5, col: 5, orientation: 'H' },
      { row: 5, col: 7, orientation: 'H' },
      { row: 3, col: 0, orientation: 'H' },
      { row: 3, col: 2, orientation: 'H' },
      { row: 3, col: 4, orientation: 'H' },
      { row: 3, col: 6, orientation: 'H' },
      { row: 1, col: 1, orientation: 'H' },
      { row: 1, col: 3, orientation: 'H' },
      { row: 1, col: 5, orientation: 'H' },
      { row: 1, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p10',
    title: 'Le défi ultime',
    description: "Le parcours le plus long et le plus exigeant. Aucune erreur ne pardonne.",
    maxMoves: 38,
    walls: [
      { row: 7, col: 1, orientation: 'H' },
      { row: 7, col: 3, orientation: 'H' },
      { row: 7, col: 5, orientation: 'H' },
      { row: 7, col: 7, orientation: 'H' },
      { row: 5, col: 0, orientation: 'H' },
      { row: 5, col: 2, orientation: 'H' },
      { row: 5, col: 4, orientation: 'H' },
      { row: 5, col: 6, orientation: 'H' },
      { row: 3, col: 1, orientation: 'H' },
      { row: 3, col: 3, orientation: 'H' },
      { row: 3, col: 5, orientation: 'H' },
      { row: 3, col: 7, orientation: 'H' },
      { row: 1, col: 0, orientation: 'H' },
      { row: 1, col: 2, orientation: 'H' },
      { row: 1, col: 4, orientation: 'H' },
      { row: 1, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
];
