import type { Position, Wall } from './gameLogic';

export interface Puzzle {
  id: string;
  title: string;
  description: string;
  hint: string;
  maxMoves: number;
  walls: Wall[];
  p1Start: Position;
  p2Start: Position;
}

export const PUZZLES: Puzzle[] = [
  {
    id: 'p1',
    title: 'Premier pas',
    description: 'La cible est juste devant vous : rejoignez la ligne opposée en un seul mouvement.',
    hint: 'Avancez d’une case vers le bas, sans poser de mur.',
    maxMoves: 1,
    walls: [],
    p1Start: { r: 7, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p2',
    title: 'Petit détour',
    description: 'Un mur ferme le passage central. Trouvez le plus petit détour pour reprendre votre route.',
    hint: 'Décalez-vous d’abord sur le côté, puis revenez dans l’axe.',
    maxMoves: 3,
    walls: [{ row: 6, col: 4, orientation: 'H' }],
    p1Start: { r: 6, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p3',
    title: 'Sous pression',
    description: 'Le barrage apparaît au milieu du plateau. Gardez votre direction tout en changeant de colonne.',
    hint: 'Un détour latéral suffit : observez les deux extrémités du mur.',
    maxMoves: 5,
    walls: [{ row: 4, col: 4, orientation: 'H' }],
    p1Start: { r: 4, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p4',
    title: 'Le long chemin',
    description: 'Deux barrières décalées vous obligent à choisir le bon côté avant de remonter.',
    hint: 'Ne revenez pas au centre trop tôt : alignez-vous avec l’ouverture suivante.',
    maxMoves: 5,
    walls: [
      { row: 6, col: 4, orientation: 'H' },
      { row: 6, col: 2, orientation: 'H' },
    ],
    p1Start: { r: 6, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p5',
    title: 'Le grand détour',
    description: 'Deux segments ferment l’axe central. Une trajectoire latérale vous permet de rejoindre la cible en six coups.',
    hint: 'Commencez par vous écarter du barrage, puis remontez dès que la colonne est libre.',
    maxMoves: 6,
    walls: [
      { row: 3, col: 4, orientation: 'H' },
      { row: 3, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 3, c: 4 },
    p2Start: { r: 0, c: 4 },
  },
  {
    id: 'p6',
    title: 'Le zigzag',
    description: 'Deux rangées alternent leurs ouvertures. Traversez le plateau en largeur pour trouver chaque brèche.',
    hint: 'Les ouvertures changent de côté : préparez le prochain virage avant de franchir la rangée.',
    maxMoves: 22,
    walls: [
      { row: 5, col: 0, orientation: 'H' },
      { row: 5, col: 2, orientation: 'H' },
      { row: 5, col: 4, orientation: 'H' },
      { row: 5, col: 6, orientation: 'H' },
      { row: 2, col: 1, orientation: 'H' },
      { row: 2, col: 3, orientation: 'H' },
      { row: 2, col: 5, orientation: 'H' },
      { row: 2, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p7',
    title: 'Le triple barrage',
    description: 'Trois barrages successifs vous attendent, avec une brèche différente à chaque niveau.',
    hint: 'Construisez un zigzag régulier : une rangée à gauche, la suivante à droite.',
    maxMoves: 30,
    walls: [
      { row: 6, col: 0, orientation: 'H' },
      { row: 6, col: 2, orientation: 'H' },
      { row: 6, col: 4, orientation: 'H' },
      { row: 6, col: 6, orientation: 'H' },
      { row: 4, col: 1, orientation: 'H' },
      { row: 4, col: 3, orientation: 'H' },
      { row: 4, col: 5, orientation: 'H' },
      { row: 4, col: 7, orientation: 'H' },
      { row: 2, col: 0, orientation: 'H' },
      { row: 2, col: 2, orientation: 'H' },
      { row: 2, col: 4, orientation: 'H' },
      { row: 2, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p8',
    title: "L'inversion",
    description: 'Le triple barrage revient, mais son rythme est inversé. Votre premier détour donne la clé du parcours.',
    hint: 'Oubliez le puzzle précédent et repérez chaque ouverture avant d’avancer.',
    maxMoves: 30,
    walls: [
      { row: 6, col: 1, orientation: 'H' },
      { row: 6, col: 3, orientation: 'H' },
      { row: 6, col: 5, orientation: 'H' },
      { row: 6, col: 7, orientation: 'H' },
      { row: 4, col: 0, orientation: 'H' },
      { row: 4, col: 2, orientation: 'H' },
      { row: 4, col: 4, orientation: 'H' },
      { row: 4, col: 6, orientation: 'H' },
      { row: 2, col: 1, orientation: 'H' },
      { row: 2, col: 3, orientation: 'H' },
      { row: 2, col: 5, orientation: 'H' },
      { row: 2, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p9',
    title: 'Le grand serpent',
    description: 'Quatre rangées organisent un long serpent de passages. La patience compte autant que la direction.',
    hint: 'Restez près de l’ouverture que vous venez de franchir pour préparer le prochain changement de côté.',
    maxMoves: 40,
    walls: [
      { row: 7, col: 0, orientation: 'H' },
      { row: 7, col: 2, orientation: 'H' },
      { row: 7, col: 4, orientation: 'H' },
      { row: 7, col: 6, orientation: 'H' },
      { row: 5, col: 1, orientation: 'H' },
      { row: 5, col: 3, orientation: 'H' },
      { row: 5, col: 5, orientation: 'H' },
      { row: 5, col: 7, orientation: 'H' },
      { row: 3, col: 0, orientation: 'H' },
      { row: 3, col: 2, orientation: 'H' },
      { row: 3, col: 4, orientation: 'H' },
      { row: 3, col: 6, orientation: 'H' },
      { row: 1, col: 1, orientation: 'H' },
      { row: 1, col: 3, orientation: 'H' },
      { row: 1, col: 5, orientation: 'H' },
      { row: 1, col: 7, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
  {
    id: 'p10',
    title: 'Le défi ultime',
    description: 'Le défi final combine quatre barrages inversés et une limite stricte de mouvements.',
    hint: 'Anticipez deux rangées à l’avance : chaque détour prépare le suivant.',
    maxMoves: 38,
    walls: [
      { row: 7, col: 1, orientation: 'H' },
      { row: 7, col: 3, orientation: 'H' },
      { row: 7, col: 5, orientation: 'H' },
      { row: 7, col: 7, orientation: 'H' },
      { row: 5, col: 0, orientation: 'H' },
      { row: 5, col: 2, orientation: 'H' },
      { row: 5, col: 4, orientation: 'H' },
      { row: 5, col: 6, orientation: 'H' },
      { row: 3, col: 1, orientation: 'H' },
      { row: 3, col: 3, orientation: 'H' },
      { row: 3, col: 5, orientation: 'H' },
      { row: 3, col: 7, orientation: 'H' },
      { row: 1, col: 0, orientation: 'H' },
      { row: 1, col: 2, orientation: 'H' },
      { row: 1, col: 4, orientation: 'H' },
      { row: 1, col: 6, orientation: 'H' },
    ],
    p1Start: { r: 0, c: 4 },
    p2Start: { r: 8, c: 4 },
  },
];
